name: Merge Update to Main

on:
  schedule:
    # Executa o workflow às 03:00 UTC de 01/01/2024
    - cron: '0 3 1 1 *'  # 3:00 UTC no dia 01/01
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Git
      - name: Set up Git
        run: |
          git config user.name "ThiagoSousa81"
          git config user.email "thiagosousa81@gmail.com"

      # Checkout da branch update e merge na main
      - name: Checkout update branch
        run: git checkout update

      - name: Merge update into main
        run: |
          git checkout main
          git pull origin main
          git merge update --no-ff -m "Merge branch 'update' into 'main'"
        
      # Push das mudanças para o repositório
      - name: Push changes
        run: |
          git push origin main
