name: Merge Update to Main

on:
  schedule:
    # Executa o workflow às 03:00 UTC de 01/01/2025
    - cron: '0 3 1 1 *'  # 3:00 UTC no dia 01/01
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Git
      - name: Set up Git
        run: |
          git config user.name "ThiagoSousa81"
          git config user.email "thiagosousa81@gmail.com"

      # Checkout da branch update
      - name: Checkout update branch
        run: git checkout update

      # Forçar o README.md da update a substituir o da main
      - name: Replace README.md from update branch to main
        run: |
          git checkout main
          git pull origin main
          git checkout update -- README.md  # Substitui o README.md da branch main pelo da branch update

      # Commit e push das mudanças para o repositório
      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "§ - Happy new year - §"
          git push origin main
