name: Snake Game

on:
  push:
    branches:
      - main
      - update
  schedule:
    # Atualiza a cada 5 horas
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout do repositório
    - uses: actions/checkout@v3  # Atualizado para a versão v3, mais estável

    # Gerar o gráfico do Snake Game (GIF ou SVG)
    - uses: Platane/snk@v3
      with:
        # github user name to read the contribution graph from (**required**)
        # using action context var `github.repository_owner` or specified user
        github_user_name: ${{ github.repository_owner }}

        # list of files to generate.
        # one file per line. Each output can be customized with options as query string.
        #
        #  supported options:
        #  - palette:     A preset of color, one of [github, github-dark, github-light]
        #  - color_snake: Color of the snake
        #  - color_dots:  Coma separated list of dots color.
        #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
        #                 Exactly 5 colors are expected.
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        
    # Verifica o status do git (para depuração)
    - run: git status

    # Configurar usuário git para fazer o commit
    - name: Set up Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Commit e push das imagens geradas
    - name: Commit and push the generated files
      run: |
        git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
        git commit -m "Add Snake Game contribution grid"
        git push origin main  # Ou 'update', dependendo da sua branch principal
